query_build = {
    "class" : [],
    "mouthd" : [],
    "mouthr1" : [],
    "mouthr2" : [],
    "eyesd" : [],
    "eyesr1" : [],
    "eyesr2" : [],
    "earsd" : [],
    "earsr1" : [],
    "earsr2" : [],
    "backd" : [],
    "backr1" : [],
    "backr2" : [],
    "taild" : [],
    "tailr1" : [],
    "tailr2" : [],
    "hornd" : [],
    "hornr1" : [],
    "hornr2" : [],
    "speedMin": [],
    "speedMax": [],
    "healthMin": [],
    "healthMax": [],
    "skillMin": [],
    "skillMax": [],
    "moraleMin": [],
    "moraleMax": [],
    "breedCount": [],
    "pureness":[],
    "geneticPurityMin":[],
    "geneticPurityMax":[],
}

axie_details = {
    "id":"",
    "priceUsd":"",
    "priceEth":"",
    "floorDiff":"",
    "eyes":"",
    "ears":"",
    "mouth":"",
    "horn":"",
    "back":"",
    "tail":"",
    "class":"",
    "breedCount":""
}

